### PR TITLE
explain how to build on Debian stretch too

### PR DESCRIPTION
**Pull request by h01ger**
Not everybody has docker easily available (eg ironically QubesOS users) so I figured it's useful to provide simple step-by-step instructions how to build this on a bare Debian system.

Signed-off-by: Holger Levsen <holger@layer-acht.org>

### CODE REVIEW

**Comment by talex5** [comment]
I removed the non-Docker instructions because it was too hard to keep them up-to-date:

https://github.com/talex5/qubes-mirage-firewall/commit/583366b22bf78be060bf3ab7be353bc7a3479f79#diff-04c6e90faac2675aa89e2176d2eec7d8

It's much easier to debug build problems if everyone is using the same versions and less confusing for users to have one set of instructions. Docker is easily available in Qubes (the README shows how to install it), although you might need to make its cache persistent if you're not using using a standalone VM for building (otherwise I guess you'll need to re-download the base image after rebooting).

(example of user problem: http://roscidus.com/blog/blog/2016/01/01/a-unikernel-firewall-for-qubesos/#comment-3090627184)

Of course, people are welcome to install without Docker. But I think only mirage devs are going to want to do that, and they'll already know how to do it.

**Comment by h01ger** [comment]
Hi Thomas,

On Sun, Dec 03, 2017 at 02:53:43PM +0000, Thomas Leonard wrote:
> I removed the non-Docker instructions because it was too hard to keep them up-to-date:

thanks for explaining. (& fair enough!)

> It's much easier to debug build problems if everyone is using the same versions 
> and less confusing for users to have one set of instructions. 

true.

> Docker is easily available in Qubes (the README shows how to install it),
> although you might need to make its cache persistent if you're not using
> using a standalone VM for building (otherwise I guess you'll need to
> re-download the base image after rebooting).

see, I wouldn't call that easy.

> Of course, people are welcome to install without Docker. But I think only
> mirage devs are going to want to do that, and they'll already know how to do it.

I disagree & I'm not a mirage developer :) But you probably have a point
that this can also be fixed by improving the documentation on the mirage
side.

And last not least, I've solved it for me, so this works for me! ;)

In related news I plan to try qubes-mirage-firewall shortly and will
then try to come up with a patch documentating it's usage and
configuration. (issue #18)


-- 
cheers,
	Holger

**Comment by h01ger** [comment]
On Sun, Dec 03, 2017 at 07:07:00AM -0800, Holger Levsen wrote:
> > Docker is easily available in Qubes (the README shows how to install it),
> > although you might need to make its cache persistent if you're not using
> > using a standalone VM for building (otherwise I guess you'll need to
> > re-download the base image after rebooting).
> see, I wouldn't call that easy.

that alone maybe could be described as easy, but with Debian Qubes you also
need to install the kernel headers from dom0 or run the Qube with its own
Debian kernel, and those two bits are not easy in my book.


-- 
cheers,
	Holger

**Comment by talex5** [comment]
I don't recall having to do anything like that (I'm running Docker in a standalone Debian Qube).

Looking at my config, I see I'm using `Storage Driver: btrfs`, where `/var/lib/docker` is a btrfs filesystem. But I don't think that's necessary. I just tried running it with `sudo dockerd --data-root=/tmp/docker` and that worked too (it automatically used `Storage Driver: overlay2`).

The kernel is

```
$ uname -a
Linux dev 4.9.56-21.pvops.qubes.x86_64 #1 SMP Tue Oct 17 23:58:50 UTC 2017 x86_64 GNU/Linux
```

**Comment by h01ger** [comment]
On Sun, Dec 03, 2017 at 04:51:49PM +0000, Thomas Leonard wrote:
> I don't recall having to do anything like that (I'm running Docker in a standalone Debian Qube).

I think it would be more productive to see whether we can get the same
checksum for a build with docker and without. AFAwe know (from tests
with reprotest), qubes-mirage-firewalls builds reproducible indepent
of most standard variations except the build path (date, time, locale,
etc doesnt matter and can vary..), provided the same ocaml version and
depends obviously. so my current question is: in which path does docker
build?


-- 
cheers,
	Holger

**Comment by talex5** [comment]
The version of gcc also affects it, IIRC. It changed after a minor update to Debian once at least.

**Comment by talex5** [comment]
(and docker builds it in `/home/opam/qubes-mirage-firewall` - see the Dockerfile for the exact commands it is running)

**Comment by h01ger** [comment]
On Mon, Dec 04, 2017 at 07:59:04PM +0000, Thomas Leonard wrote:
> The version of gcc also affects it, IIRC. It changed after a minor update to Debian once at least.

yes, sure. what I ment with variations in this context was the
environment *besides* the exact same toolchain.

in build-with-docker.sh there is a SHA2 hash, which is for the unikernel
and not for the qubes taylored tarball, right? cause the tarball shows 
timestamp variations for the files in it...

btw, do you have plans/blockers to update to a debian 9 docker template? Maybe
I can reproduce that SHA2 when building natively? ;)

Thanks!


-- 
cheers,
	Holger

**Comment by talex5** [comment]
It should be possible to make the tarball generation reproducably too. The other files inside it are just dummy placeholders to make Qubes happy. Ideally they wouldn't be there.

You should be able to test on any version of Debian just by changing the header of the Dockerfile.

**Comment by h01ger** [comment]
On Thu, Dec 07, 2017 at 02:37:24AM -0800, Thomas Leonard wrote:
> It should be possible to make the tarball generation reproducably too. 

sure. tar just need to be told to use SOURCE_DATE_EPOCH for the mtimes
of the tar members. if building from git, setting S_D_E to the date of
the last commit is easy, only if not building from git, setting S_D_E
is more difficult, though setting it to 0 in those cases is an easy way
out.

https://reproducible-builds.org/specs/source-date-epoch/

> The other files inside it are just dummy placeholders to make Qubes happy. Ideally they wouldn't be there.

sure, but they are there.

> You should be able to test on any version of Debian just by changing the header of the Dockerfile.

cool.


-- 
cheers,
	Holger

**Pull request closed without merging**
