### PR TITLE
remove gui code, not needed anymore in Qubes 4.1

### LINKED ISSUE #62: Remove GUI code
Qubes 3 required us to connect to the GUI daemon in dom0 before it would consider the firewall to have started. Qubes 4 no longer requires this (see `man qvm-features`).

Remove the GUI code from `unikernel.ml` and test/update the installation instructions in `README.md` to make sure they work with the new system.

### PR DESCRIPTION
**Pull request by palainp**
This PR should fix #62 :)

### CODE REVIEW

**Comment by hannesm** [comment]
looks fine to me. should we update the checksum in "build-with-docker.sh"?

**Comment by palainp** [comment]
I will, but I wanted to wait for the mirage-qubes update to also have qrexecv3. Or is it better in a separate PR?

**Comment by hannesm** [comment]
fine to do with an update of opam-repository (and #142 #145 if that works fine for you)

**Comment by hannesm** [comment]
merged as part of #149

**Pull request closed without merging**
