### PR TITLE
Test memory

### PR DESCRIPTION
**Pull request by hannesm**
see dscussion in #143 /cc @palainp

### CODE REVIEW

**Comment by palainp** [comment]
Thanks @hannesm for this PR.

With the change to `Xen_os.quick_stat()`, I expected to have some adjustments to make here. Do you think it might be useful to try `GC.compact()` instead of just `GC.full_major()` when the memory pressure test is triggered?

**Comment by hannesm** [comment]
Hmm, do you mean `Gc.compact` is faster? It may be sufficient -- the main thing is that the major cycle finishes and finalizers are executed (to free up bigarray data) -- as far as I know.

At the same time, unless I'm wrong we're using the (default since 4.13) best-fit GC strategy, where compactions are not needed (but in any way, both Gc.compact and Gc.full_major do the major collection -- I'm not entirely sure what the difference is) -- do you observe speed-wise a huge difference?

**Comment by palainp** [comment]
I haven't noticed any speed difference and the documentation warns that `Gc.compact` is slower (https://v2.ocaml.org/api/Gc.html#VALcompact). Thanks for reminding me that best-fit is now the default and that there is no need to compact, it's probably not worth investigating so much that idea.

**Comment by hannesm** [comment]
merged as part of #149

**Pull request closed without merging**
