### PR TITLE
use tcpip 3.7, ethernet, arp, mirage-nat 1.1.0 

### PR DESCRIPTION
**Pull request by yomimono**
This requires ~~the (pending) release of~~ mirage-nat 1.1.0 ( https://github.com/ocaml/opam-repository/pull/13725 ).

### CODE REVIEW

**Comment by yomimono** [comment]
This will also need some updates to `Dockerfile`, which I'm not sure how to discover the correct values for.  I don't currently a working `docker` anywhere, so it would be nice if I could leave that up to someone who has access to and cares about this.

**Comment by talex5** [comment]
This looks generally good. Do you have any measurements of the performance hit from using the new API? I assume it will make the firewall a little faster for ARP messages, but slower for IP packets (since the new fill API requires an extra zeroing step). I'm not too bothered about performance myself, but I know some people care about this.

**Comment by yomimono** [comment]
I was interested in this too, so set up a quick test.  `sys-net` is running `iperf3 -s`; downstream from it is `mirage-fw-test`, which is loaded first with the current master for the first test, then with a version built from this PR and the updated upstream packages in the second test.  `mirage-fw-test` has a Linux client which runs `iperf -c` to connect to `sys-net`.

```
-----------------------------------------------------------
Server listening on 5201
-----------------------------------------------------------
Accepted connection from 10.137.0.25, port 14324
[  5] local 10.137.0.5 port 5201 connected to 10.137.0.25 port 24074
[ ID] Interval           Transfer     Bandwidth
[  5]   0.00-1.00   sec  13.2 MBytes   111 Mbits/sec                  
[  5]   1.00-2.00   sec  13.6 MBytes   114 Mbits/sec                  
[  5]   2.00-3.00   sec  12.6 MBytes   106 Mbits/sec                  
[  5]   3.00-4.00   sec  12.6 MBytes   106 Mbits/sec                  
[  5]   4.00-5.00   sec  12.3 MBytes   103 Mbits/sec                  
[  5]   5.00-6.00   sec  14.0 MBytes   117 Mbits/sec                  
[  5]   6.00-7.00   sec  15.1 MBytes   127 Mbits/sec                  
[  5]   7.00-8.00   sec  14.6 MBytes   122 Mbits/sec                  
[  5]   8.00-9.00   sec  14.4 MBytes   120 Mbits/sec                  
[  5]   9.00-10.00  sec  12.9 MBytes   108 Mbits/sec                  
[  5]  10.00-10.04  sec   362 KBytes  67.8 Mbits/sec                  
- - - - - - - - - - - - - - - - - - - - - - - - -
[ ID] Interval           Transfer     Bandwidth
[  5]   0.00-10.04  sec  0.00 Bytes  0.00 bits/sec                  sender
[  5]   0.00-10.04  sec   136 MBytes   113 Mbits/sec                  receiver
-----------------------------------------------------------
Server listening on 5201
-----------------------------------------------------------


Accepted connection from 10.137.0.25, port 11056
[  5] local 10.137.0.5 port 5201 connected to 10.137.0.25 port 19666
[ ID] Interval           Transfer     Bandwidth
[  5]   0.00-1.00   sec  29.7 MBytes   249 Mbits/sec                  
[  5]   1.00-2.00   sec  24.1 MBytes   202 Mbits/sec                  
[  5]   2.00-3.00   sec  28.7 MBytes   241 Mbits/sec                  
[  5]   3.00-4.00   sec  32.1 MBytes   269 Mbits/sec                  
[  5]   4.00-5.00   sec  33.4 MBytes   281 Mbits/sec                  
[  5]   5.00-6.00   sec  34.1 MBytes   286 Mbits/sec                  
[  5]   6.00-7.00   sec  30.4 MBytes   255 Mbits/sec                  
[  5]   7.00-8.00   sec  33.3 MBytes   280 Mbits/sec                  
[  5]   8.00-9.00   sec  33.7 MBytes   283 Mbits/sec                  
[  5]   9.00-10.00  sec  32.3 MBytes   271 Mbits/sec                  
[  5]  10.00-10.04  sec  1.45 MBytes   293 Mbits/sec                  
- - - - - - - - - - - - - - - - - - - - - - - - -
[ ID] Interval           Transfer     Bandwidth
[  5]   0.00-10.04  sec  0.00 Bytes  0.00 bits/sec                  sender
[  5]   0.00-10.04  sec   313 MBytes   262 Mbits/sec                  receiver
-----------------------------------------------------------
Server listening on 5201
-----------------------------------------------------------
```

So, good news for people who care about throughput on single TCP connections, apparently.  This is a bit counterintuitive, and my best hypothesis about it involves the changeset for `mirage-nat`, which is now writing into a single buffer instead of doing several calls to `Cstruct.create` per packet via a header-specific `make_cstruct` call for each layer.  An `iperf` test with a firewall that uses the old `Nat_packet.make_cstruct` interface and then concatenates and copies the results into the buffer provided by `write` has worse performance than the new version, but not as much worse than the old version:

```
Accepted connection from 10.137.0.25, port 11056
[  5] local 10.137.0.5 port 5201 connected to 10.137.0.25 port 19666
[ ID] Interval           Transfer     Bandwidth
[  5]   0.00-1.00   sec  24.7 MBytes   207 Mbits/sec                  
[  5]   1.00-2.00   sec  23.3 MBytes   195 Mbits/sec                  
[  5]   2.00-3.00   sec  21.9 MBytes   184 Mbits/sec                  
[  5]   3.00-4.00   sec  20.8 MBytes   175 Mbits/sec                  
[  5]   4.00-5.00   sec  21.4 MBytes   180 Mbits/sec                  
[  5]   5.00-6.00   sec  22.3 MBytes   187 Mbits/sec                  
[  5]   6.00-7.00   sec  22.8 MBytes   191 Mbits/sec                  
[  5]   7.00-8.00   sec  18.7 MBytes   157 Mbits/sec                  
[  5]   8.00-9.00   sec  20.8 MBytes   175 Mbits/sec                  
[  5]   9.00-10.00  sec  24.1 MBytes   202 Mbits/sec                  
[  5]  10.00-10.04  sec   951 KBytes   189 Mbits/sec                  
- - - - - - - - - - - - - - - - - - - - - - - - -
[ ID] Interval           Transfer     Bandwidth
[  5]   0.00-10.04  sec  0.00 Bytes  0.00 bits/sec                  sender
[  5]   0.00-10.04  sec   222 MBytes   185 Mbits/sec                  receiver
-----------------------------------------------------------
Server listening on 5201
-----------------------------------------------------------
```

I'd need to do some further profiling to get a better answer about this.

**Comment by hannesm** [comment]
these are good results :) my intuition was indeed that tcpip 3.7.1 / mirage-net 2.0.0 / mirage-protocols 2.0.0 would speed things up (due to less allocations on the write path). when i did some measurements of an iperf-unikernel, I didn't get such a speedup (and was a bit disappointed). I'm glad it has an affect here :smiley:

**Comment by talex5** [comment]
OK, I'm convinced :-D

Tried iperf here too (had to disable an iptables rule in sys-net that was blocking it), and also got very nice results (`53.7 Mbits/sec` -> `206 Mbits/sec`)!!

**Pull request merged**
