### PR TITLE
Minor cleanups

### PR DESCRIPTION
**Pull request by talex5**
- Fix Lwt.4.5.0 in the Dockerfile for faster builds (avoids downgrading in next step)
- Remove unused Clock argument to Uplink

### CODE REVIEW

**Comment by xaki23** [comment]
"ported" the "faster build" part to Makefile.builder, works awesome. 
5-6 min for the full builder-build.
how do i +1 this for merge?

workflow question ... do you want that additional change:
 - as a review/comment here, 
 - a PR against talex5:cleanup while this is still open or 
 - a PR against mirage:master after this is merged?

perhaps we can get this capsulated in a way that the "pre-deps" need to be updated only in one place in the future? 
put the "opam depext" call into a separate .sh and call that from both dockerfile + makefile?
that smells, but less than double updates perhaps?

**Comment by talex5** [comment]
At some point mirage will move to building with dune. Depending on how it does that, it might solve the problem by letting us specify the version of mirage in the dune file.

**Comment by talex5** [comment]
I've merge it now. Feel free to make a separate PR updating `Makefile.builder`.

**Comment by xaki23** [comment]
> I've merge it now. Feel free to make a separate PR updating `Makefile.builder`.

https://github.com/mirage/qubes-mirage-firewall/pull/91

**Pull request merged**
