### PR TITLE
update opam repository commit to use solo5 0.9 and mirage 4.8.1

### PR DESCRIPTION
**Pull request by hannesm**

### CODE REVIEW

**Comment by palainp** [comment]
Thank you! While updating things, do you think it's worth updating the debian docker image, debian snapshots, and opam-overlays as well?

**Comment by hannesm** [comment]
> Thank you! While updating things, do you think it's worth updating the 
> debian docker image

I don't know

> debian snapshots,

I don't know

> and opam-overlays as well?

there's been no change as far as I can tell.

**Comment by palainp** [comment]
I don't know neither about the debian ones and I haven't heard anything critical about it, so I'm keen to keep my caches without having to download too many things :)

For opam-overlays, there were lwt_ppx and something about colombe since the current commit hash, but I'm unsure if we need the updates or not.

**Comment by hannesm** [comment]
we don't ;)

**Comment by palainp** [comment]
Sorry for the force push, I had to remove the last commit to be able to merge, and I'll reintroduce the updated hashsum value on main.

**Pull request merged**
