### PR TITLE
My_nat.free_udp_port: avoid looping forever, use last_resort_port earlier

### PR DESCRIPTION
**Pull request by hannesm**
This avoids using the entire CPU. See #158 for the issue description (especially my comment https://github.com/mirage/qubes-mirage-firewall/issues/158#issuecomment-1307610459).

### CODE REVIEW

**Comment by palainp** [comment]
Thanks for that PR. After some times setting up correctly my mirage-fw I can confirm that it doesn't burn the CPU anymore.
LGTM (together with the mirage-nat update that also helps in solving this issue)!

**Comment by hannesm** [comment]
I would like to verify first that the mirage-nat change (and 3.0.1 release) fixes the issue. This change here is "purely cosmetical" and shouldn't be needed. Though it as well helps to avoid busy loops (since the `free_udp_port` will be bounded).

While working on this, another issue is how DNS replies are handled with a single global mailbox (Lwt_mvar)
- a DNS query is sent out
- whenever a DNS reply is received, this is pushed into the mailbox

This means there can be concurrent requests with unclear ordering, and also the Lwt_mvar.put (in uplink) can block if there's nobody reading the mailbox (which only my_dns is). So that code should be revised that DNS replies are matching the requests, and there's no blocking behaviour if more replies are received than requests that were sent. Especially evil since there's a timeout which cancels the Lwt_mvar.take...

**Comment by palainp** [comment]
Thanks @hannesm for your amazing work on that points!
I can confirm that the PR with mirage-nat alone (without this PR) permit to not overload CPU, but I'll feel better to have a bounded loop :)

**Comment by hannesm** [comment]
this has been part of https://github.com/mirage/qubes-mirage-firewall/pull/163 and the 0.8.3 release

**Pull request closed without merging**
